// Mocks generated by Mockito 5.4.4 from annotations
// in atividade0909/test/agentes/agentes.repository.test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:atividade0909/models/agente.dart' as _i4;
import 'package:atividade0909/repositories/agenteRepository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AgentesReposisory].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentesReposisory extends _i1.Mock implements _i2.AgentesReposisory {
  @override
  _i3.Future<List<_i4.Agente>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Agente>>.value(<_i4.Agente>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Agente>>.value(<_i4.Agente>[]),
      ) as _i3.Future<List<_i4.Agente>>);

  @override
  _i3.Future<Iterable<_i4.Agente>> findByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByName,
          [name],
        ),
        returnValue: _i3.Future<Iterable<_i4.Agente>>.value(<_i4.Agente>[]),
        returnValueForMissingStub:
            _i3.Future<Iterable<_i4.Agente>>.value(<_i4.Agente>[]),
      ) as _i3.Future<Iterable<_i4.Agente>>);
}
